export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import '../globals.css';
import { ToastContainer } from 'react-toastify';

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <ToastContainer
          autoClose={1200}
        />
        {children}
      </body>
    </html>
  )
}
