import { Geist, Geist_Mono } from "next/font/google";
import '../globals.css';
import Header from "@/components/website/Header";
import Footer from "@/components/website/Footer";
import Storeprovider from "@/components/Storeprovider";
import { ToastContainer } from "react-toastify";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Shop-India",
  description: "Generated by create next app",
  icons: {
    icon: "/2.png", // ✅ this sets your favicon
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Storeprovider>
        <body className="bg-[#E2E4EB]">
          <Storeprovider >
            <ToastContainer
              autoClose={1200}
            />
            <Header />
            {children}
            <Footer />
          </Storeprovider>

        </body>
      </Storeprovider>
    </html>
  );
}
